add support for comparison database functions
mongodb-labs/django-mongodb pull request #46
Opened 2024-06-05 23:54 UTC by timgraham

2024-06-11 20:26 UTC, Jibola approved these changes

2024-06-11 20:26 UTC, Jibola requested changes
Two points and then everything else looks good!

2024-06-11 20:51 UTC, timgraham commented on django_mongodb/features.py
> +        "db_functions.tests.FunctionTests.test_function_as_filter",
Yes, if feasible. Actulaly, in the latest push I added a workaround for $strLenCP crashing on null:
`{"$cond": {"if": {"$eq": [lhs_mql, None]}, "then": None, "else": {"$strLenCP": lhs_mql}}}`.

2024-06-11 20:51 UTC, timgraham commented on django_mongodb/functions.py
> +    return {"$cond": {"if": {"$eq": [expr1, expr2]}, "then": None, "else": expr1}}
Well spotted

2024-06-11 20:51 UTC, timgraham commented on django_mongodb/functions.py
> +    return {"$substrCP": lhs}
Okay

2024-06-12 00:03 UTC, WaVEV approved these changes

2024-06-12 16:44 UTC, Jibola approved these changes

2024-06-12 17:51 UTC, merged