allow QuerySet.count() to query multiple collections
mongodb-labs/django-mongodb pull request #78
Opened 2024-07-11 19:04 UTC by timgraham

2024-07-12 03:33 UTC, WaVEV commented on django_mongodb/features.py
> +            # "lookup.tests.LookupTests.test_lookup_collision_distinct",
This todo is done?

2024-07-12 03:44 UTC, WaVEV commented
I have been working on a similar task, specifically because the aggregate includes `count`. In my opinion, it is ok to merge this code, even though the majority of it will likely be moved or replaced.

2024-07-12 03:46 UTC, WaVEV requested changes
Minor thing: Solve the TODO

2024-07-12 08:58 UTC, timgraham commented
The todo is because there's a corresponding patch to the Django fork that I'll merge in advance of this one:
```diff
diff --git a/tests/lookup/tests.py b/tests/lookup/tests.py
index a198a13b62..aa4ed46b98 100644
--- a/tests/lookup/tests.py
+++ b/tests/lookup/tests.py
@@ -1112,6 +1112,10 @@ class LookupTests(TestCase):
         self.assertEqual(Game.objects.filter(season__gt__in=[222, 333]).count(), 5)
         self.assertEqual(Game.objects.filter(season__gt__gt=111).count(), 5)
 
+    def test_lookup_collision_distinct(self):
+        # These were separated from the above test because distinct() isn't
+        # supported.
+
         # Players who played in 2009
         self.assertEqual(
   
```
I don't want to merge that until this is approved since it would cause other builds to fail in the meantime.

2024-07-16 13:31 UTC, WaVEV approved these changes

2024-07-16 15:05 UTC, merged